name: Lobby
version: 1.5
author: lusu007
description: Lobbymanaging Plugin

main: net.blockbreaker.lobby.Lobby
load: POSTWORLD
depend: [EffectLib, TitleAPI]

commands:
  holo:
    aliases: h
    description: Setzt Hologramme